name: AutoCheckBJMF

on:
  workflow_dispatch:

env:
  ClassID: ${{ secrets.ClassID }}
  X: ${{ secrets.X }}
  Y: ${{ secrets.Y }}
  ACC: ${{ secrets.ACC }}
  SearchTime: ${{ secrets.SEARCHTIME }}
  MyCookie: ${{ secrets.MYCOOKIE }}
  token: ${{ secrets.TOKEN }}

jobs:
  checkin:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: python -m pip install --upgrade requests beautifulsoup4 schedule

      - name: Checkin
        run: python main.py
